version: '3.8'
services:
  app:
    build: .
    command: ["vendor/bin/phpunit", "--colors=always"]
    volumes:
      - .:/var/www/html
    depends_on:
      - test-db
    environment:
      - DB_HOST=test-db
      - DB_NAME=test_db

  test-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
